#!/usr/bin/env python3
"""Generate secure_boot_hashes.c with SHA-256 digests of embedded ELF binaries.

Usage: python3 gen_secure_boot_hashes.py output.c elf1.elf elf2.elf ...
"""
import sys
import hashlib

def main():
    if len(sys.argv) < 3:
        print(f"Usage: {sys.argv[0]} output.c elf1.elf elf2.elf ...", file=sys.stderr)
        sys.exit(1)

    output_path = sys.argv[1]
    elf_paths = sys.argv[2:]

    lines = []
    lines.append('// Auto-generated by gen_secure_boot_hashes.py -- DO NOT EDIT')
    lines.append('#include "types.h"')
    lines.append('#include "sha256.h"')
    lines.append('')
    lines.append('typedef struct {')
    lines.append('    uint8_t hash[SHA256_DIGEST_SIZE];')
    lines.append('} secure_boot_hash_entry_t;')
    lines.append('')

    entries = []
    for path in elf_paths:
        with open(path, 'rb') as f:
            data = f.read()
        digest = hashlib.sha256(data).digest()
        basename = path.split('/')[-1]
        entries.append((basename, digest))

    lines.append(f'static const secure_boot_hash_entry_t secure_boot_known_hashes[] = {{')
    for basename, digest in entries:
        hex_bytes = ', '.join(f'0x{b:02x}' for b in digest)
        lines.append(f'    /* {basename} */')
        lines.append(f'    {{ {{ {hex_bytes} }} }},')
    lines.append(f'}};')
    lines.append('')
    lines.append(f'#define SECURE_BOOT_NUM_HASHES (sizeof(secure_boot_known_hashes) / sizeof(secure_boot_known_hashes[0]))')

    with open(output_path, 'w') as f:
        f.write('\n'.join(lines) + '\n')

    print(f"[SECURE_BOOT] Generated {output_path} with {len(entries)} hashes")

if __name__ == '__main__':
    main()
